---
title: "ManyPrimates1_Phylogenetic_Analysis"
output:
  html_notebook:
    code_folding: hide
    css: style.css
    theme: paper
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
library(tidyverse)
library(readxl)
library(googledrive)
library(brms)
```

# Read in STM data file

```{r}
data <- read_csv("../data/merged_data/ManyPrimates_mp1_merged_data.csv")
```
```{r}
# drive_download("https://docs.google.com/spreadsheets/d/1RCLvbNWFph6bHvupetx7RDiAu5BWXK6PumgRo44ZoeM/edit#gid=1909432990",
#                path = "../data/species_predictors.xlsx", 
#                overwrite = T)

species_data <- read_xlsx("../data/species_predictors.xlsx", sheet = 1)%>% 
  filter(row_number() <= n()-3)%>% # remove last rows which contained a note
  mutate_if(is.character, tolower)

```

Merge experimental data with species-level predictors

Species `hamlyns_monkey` and `allens_swamp_monkey` will be excluded from the phylogenetic analysis because we did not find data for some predictors for those species. For `sichuan_snub_nosed_monkey` we actually don't have any experimental data.

```{r}
phylo_data <- data %>%
  rename(species_english = species)%>% # create a common column to merge by
  mutate(species_english = ifelse(species_english == "gorilla", "western_gorilla",species_english)) %>%# re-code gorillas to match the species names 
  left_join(species_data)%>%
  filter(species_english != "allens_swamp_monkey",
         species_english != "hamlyns_monkey",
         species_english != "sichuan_snub_nosed_monkey")

# check if there are remaining NAs for the predictors

phylo_data %>%
  filter_at(vars(22:33),any_vars(is.na(.)))


```

